name: Ebay WEB Tests
on:
  push:
    branches: [ "main" ]
jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
    - name: Get repository code
      uses: actions/checkout@v3
    - name: Install Google Chrome 

      run: |

              chmod +x ./scripts/InstallChrome.sh

                          ./scripts/InstallChrome.sh 
    - name: Test application
      run: mvn -B package --file pom.xml
