name: Ebay Web Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout reqres branch on GitHub
        uses: actions/checkout@v3
      - name: Step 2 - Set up JDK 11 
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Step 3 - Build with Maven
        run: mvn -B package --file pom.xml
      - name: Step 4 - List the current directory
        run: ls -a
      - name: Step 5 - What is in the target folder?
        run:
         cd target
         ls -a
